version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: booking-postgres
    environment:
      POSTGRES_DB: BookingDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: